### ISSUE TITLE
关于输入数据格式的问题

### ISSUE THREAD

**Issue by FYF1997** [hanzi-chai/chai#13]
您好，首先对您在汉字笔画拆分这一领域所作出的探索与研究表达敬意，在大致看完您项目的介绍后，对于项目有一些小问题，即，此算法接受的输入数据的格式是图片还是直接的电子输入？希望能够得到您的回复，谢谢！

**Comment by slbb** [comment]
> 您好，首先对您在汉字笔画拆分这一领域所作出的探索与研究表达敬意，在大致看完您项目的介绍后，对于项目有一些小问题，即，此算法接受的输入数据的格式是图片还是直接的电子输入？希望能够得到您的回复，谢谢！

问题回答：
项目所依赖的拆分数据都是内建的，包括汉字基础部件的图形数据（比如`氵``亻``又`等等），及其引用汉字的组合结构（比如`汉`引用`氵`+`又`，组合结构为左右结构等等）。
因为目前只整理了GB字集的数据，所以只能拆分GB字集。并且不能自定义选定拆分范围。
由于GB字集的拆分效果不如预期，目前工作主要以提高拆分准确度为主，之后再考虑扩充更多字集数据。

其它相关：
本项目致力于实现有理拆分，故没有采用机器学习进行图像分析，数据均为人工收集整理所得。如果想了解机器学习进行拆分相关，可浏览[利用深度学习拆分仓颉项目 by 雪齋](https://github.com/LEOYoon-Tsaw/neuro-cangjie)。
