### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zcdliuwei** [hanzi-chai/chai#14]
首先感谢您的工作，非常有意义。
这里想问一个问题：您的算法可以得到汉字每一笔的位置信息吗？
比如一个汉字，假设我是位图输入，不仅要拆出每一个笔画，还想得到每一笔在原图上的位置信息，请问这个如何做到？
感谢，期待您的回复

**Comment by slbb** [comment]
本项目并非直接采用图像信息进行计算。而是提取出最基本的结构之后通过嵌套进行拆分。比如`折`字由`扌`和`斤`组成，只分析`扌`和`斤`两个基本部件的图像信息，而不分析`折`整字的图像。所以本项目只包含 600 个左右的基本部件图像信息，并且这些图像信息是手工校对的。

**Comment by zcdliuwei** [comment]
> @zcdliuwei 本项目并非直接采用图像信息进行计算。而是提取出最基本的结构之后通过嵌套进行拆分。比如`折`字由`扌`和`斤`组成，只分析`扌`和`斤`两个基本部件的图像信息，而不分析`折`整字的图像。所以本项目只包含 600 个左右的基本部件图像信息，并且这些图像信息是手工校对的。

哦哦，我希望输入一个汉字，能拿到该汉字的每一个笔画，即知道每一个笔画的位置信息
