### ISSUE TITLE
如何调用

### ISSUE THREAD

**Issue by ouhongxu** [hanzi-chai/chai#17]
本人小白一枚，想获得某一个字的横向拆字的结果；此项目的文档我仔细看了一遍，但还是有些手足无措，您方便提供一下调用的代码吗？（获得某一个字的拆字的结果，能获得其横向拆字的结果 就更好不过了）
谢谢！

**Comment by tansongchen** [comment]
@ouhongxu 本项目已经迁移至新的[图形界面版本](https://github.com/hanzi-chai/hanzi-chai.github.io)，  ，部署位置为 https://chaifen.app ，欢迎试用
