### ISSUE TITLE
没像样的API说明文档

### ISSUE THREAD

**Issue by timberswift** [hanzi-chai/chai#18]
功能这么牛x完备的一个工具，我竟然不知道怎么用。。。

**Comment by Haiming94** [comment]
好像有发布安装包的文档：https://pypi.org/project/pychai/

**Comment by Haiming94** [comment]
不对 这个好像也不是教程

**Comment by tansongchen** [comment]
@timberswift @Haiming94 本项目已经迁移至新的[图形界面版本](https://github.com/hanzi-chai/hanzi-chai.github.io)，部署位置为 https://chaifen.app ，欢迎试用
